# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/feiya/Desktop/GAODA/GAODA/value.cache/wt [current_project]
set_property parent.project_path C:/Users/feiya/Desktop/GAODA/GAODA/value.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/feiya/Desktop/GAODA/GAODA/value.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/saw.coe
add_files C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/tri.coe
add_files C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/square.coe
add_files C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/sin.coe
read_verilog -library xil_defaultlib {
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/ad9226_sample.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/bin_to_bcd.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/color_bar.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/conv.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/dadata_amp.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/dds.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/freq_control.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/grid_display.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/key_debounce.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/key_process.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/seg_decoder.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/seg_scan.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/timing_gen_xy.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/top_key_sw_dds.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/top_osc.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/top_oscilloscope.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/top_plj.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/top_seg.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/top_value.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/OSILLISCOPE/wav_display.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/wave_sel.v
  C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/DDS/GAODA.v
}
read_ip -quiet C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/saw_rom/saw_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/saw_rom/saw_rom_ooc.xdc]

read_ip -quiet C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/tri_rom/tri_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/tri_rom/tri_rom_ooc.xdc]

read_ip -quiet C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/square_rom/square_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/square_rom/square_rom_ooc.xdc]

read_ip -quiet C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/sin_rom/sin_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/ip/sin_rom/sin_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/constrs/display_vga.xdc
set_property used_in_implementation false [get_files C:/Users/feiya/Desktop/GAODA/GAODA/value.srcs/sources_1/constrs/display_vga.xdc]


synth_design -top GAODA -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef GAODA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file GAODA_utilization_synth.rpt -pb GAODA_utilization_synth.pb"
